# Generated by Django 5.0.2 on 2024-04-18 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_water_intake', models.IntegerField(help_text='Total water intake in ml')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WaterTrackerTable',
                'unique_together': {('user', 'date', 'total_water_intake')},
            },
        ),
    ]
